CREATE TABLE IF NOT EXISTS usuario(
	id BIGINT AUTO_INCREMENT NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	nome_completo VARCHAR(255) NOT NULL,
	avatar VARCHAR(255),
	ativo BIT(1) NOT NULL,
	id_regra BIGINT NOT NULL,
	id_empresa BIGINT NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	criado_por VARCHAR(255) NOT NULL,
	modificado_por VARCHAR(255) NOT NULL,
	celular VARCHAR(9),
	telefone VARCHAR(8),
	ddd_celular VARCHAR(2),
	ddd_telefone VARCHAR(2),
	is_tecnico BIT(1),
	CONSTRAINT PK_usuario_id PRIMARY KEY (id),
	CONSTRAINT FK_usuario_id_regra FOREIGN KEY (id_regra) REFERENCES regra(id),
	CONSTRAINT FK_usuario_id_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id),
	CONSTRAINT UC_usuario_email UNIQUE (email)
);