CREATE TABLE IF NOT EXISTS tecnico (
	id BIGINT AUTO_INCREMENT NOT NULL,
	ativo BIT(1) NOT NULL,
	nome_completo VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	criado_por VARCHAR(255) NOT NULL,
	modificado_por VARCHAR(255) NOT NULL,
	CONSTRAINT PK_tecnico_id PRIMARY KEY (id),
	CONSTRAINT UC_tecnico_email UNIQUE (email)
);
