CREATE TABLE IF NOT EXISTS tipoChamado (
	id BIGINT AUTO_INCREMENT NOT NULL,
	descricao VARCHAR(50) NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	ativo BIT(1) NOT NULL,
	PRIMARY KEY (id)
);