CREATE TABLE IF NOT EXISTS empresa(
	id BIGINT AUTO_INCREMENT NOT NULL,
	cnpj VARCHAR(14) NOT NULL UNIQUE,
	razaoSocial VARCHAR(100) NOT NULL UNIQUE,
	nomeFantasia VARCHAR(100) NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	criadoPor BIGINT NOT NULL,
	modificadoPor BIGINT NOT NULL,
	ativo BIT(1) NOT NULL,
	PRIMARY KEY (id)	
);
