CREATE TABLE IF NOT EXISTS pagina(
	id BIGINT AUTO_INCREMENT NOT NULL,
	idPagina BIGINT NOT NULL,
	idRegra BIGINT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (idPagina) REFERENCES pagina (id),
	FOREIGN KEY (idRegra) REFERENCES regra (id)
);