CREATE TABLE IF NOT EXISTS pagina(
	id BIGINT AUTO_INCREMENT NOT NULL,
	link VARCHAR(50) NOT NULL,
	icon VARCHAR(50) NOT NULL,
	label VARCHAR(50) NOT NULL,
	shortLabel VARCHAR(50) NOT NULL,
	ativo BIT(1) NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	criadoPor BIGINT NOT NULL,
	modificadoPor BIGINT NOT NULL,
	PRIMARY KEY (id)
);