CREATE TABLE IF NOT EXISTS pagina(
	id BIGINT AUTO_INCREMENT NOT NULL,
	link VARCHAR(50) NOT NULL,
	icon VARCHAR(50) NOT NULL,
	label VARCHAR(50) NOT NULL,
	short_label VARCHAR(50) NOT NULL,
	ativo BIT(1) NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	criado_por VARCHAR(255) NOT NULL,
	modificado_por VARCHAR(255) NOT NULL,
	CONSTRAINT PK_pagina_id PRIMARY KEY (id)
);