CREATE TABLE IF NOT EXISTS regra(
	id BIGINT AUTO_INCREMENT NOT NULL,
	descricao VARCHAR(100) NOT NULL UNIQUE,
	ativo BIT(1) NOT NULL,
	criado DATETIME NOT NULL,
	modificado DATETIME NOT NULL,
	criadoPor BIGINT NOT NULL,
	modificadoPor BIGINT NOT NULL,
	PRIMARY KEY (id)
);