ALTER TABLE endereco 
ADD cep VARCHAR(8) NOT NULL,
ADD logradouro VARCHAR(100) NOT NULL,
ADD complemento VARCHAR(100),
ADD bairro VARCHAR(100) NOT NULL,
ADD localidade VARCHAR(500) NOT NULL,
ADD uf VARCHAR(2) NOT NULL;